name: "StaySharp_MD"
description: "Tormek T-8 sharpening and honing angle calculator with recommendations for different steel types and brands"
version: "1.0.0"
slug: "staysharp_hassio_mariadb"
url: "https://github.com/UkDC/StaySharp-Hassio-MariaDB"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
ports:
  8000/tcp: 8000
webui: "http://[HOST]:[PORT:8000]"
host_network: false
options:
  db_host: "core-mariadb"
  db_port: 3306
  db_name: "homeassistant"
  db_user: "user"
  db_password: "password"
  create_superuser: false
  superuser_username: "admin"
  superuser_email: "admin@example.com"
  superuser_password: "adminpassword"
schema:
  - name: db_host
    required: true
    type: string
    default: "core-mariadb"
  - name: db_port
    required: true
    type: integer
    default: "3306"
  - name: db_name
    required: true
    type: string
    default: "homeassistant"
  - name: db_user
    required: true
    type: string
    default: "user"
  - name: db_password
    required: true
    type: string
    default: "password"
  - name: create_superuser
    required: true
    type: boolean
    default: "false"
  - name: superuser_username
    required: false
    type: string
    default: "admin"
    condition:
      key: create_superuser
      value: true
  - name: superuser_email
    required: false
    type: string
    default: "admin@example.com"
    condition:
      key: create_superuser
      value: true
  - name: superuser_password
    required: false
    type: string
    default: "adminpassword"
    condition:
      key: create_superuser
      value: true

privileged: []
full_access: false

documentation: "README.md"
icon: "icon.png"
logo: "logo.png"

