name: "StaySharp_MD"
description: "Калькулятор Tormek T-8"
version: "1.0.0"
slug: "staysharp_hassio_mariadb"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
ports:
  8000/tcp: 8000
webui: http://[HOST]:[PORT:8000]
host_network: false
options:
  db_host: "core-mariadb"
  db_port: 3306
  db_name: "homeassistant"
  db_user: "user"
  db_password: "password"
  create_superuser: false
  superuser_username: "admin"
  superuser_email: "admin@example.com"
  superuser_password: "adminpassword"
schema:
  db_host: str
  db_port: int
  db_name: str
  db_user: str
  db_password: str
  create_superuser: bool
  superuser_username: str
  superuser_email: str
  superuser_password: str

full_access: true
