name: "StaySharp_MD"
description: "Калькулятор Tormek T-8"
version: "1.0.1"
slug: "staysharp_hassio_mariadb"
init: false
arch:
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
ports:
  8000/tcp: 8000
options:
  db_user: null
  db_password: null
  db_name: null
  db_host: core-mariadb
  db_port: 3306
  admin_username: null
  admin_password: null
  admin_email: null
schema:
  db_user: str
  db_password: password
  db_name: str
  db_host: str
  db_port: int
  admin_username: str
  admin_password: password
  admin_email: email
homeassistant: true
map:
  - config:rw
  - ssl
  - addons:rw
  - backup:rw
  - share:rw
webui: "http://[HOST]:[PORT:8000]"
