name: "StaySharp_MD"
description: "Tormek T-8 sharpening and honing angle calculator with recommendations for different steel types and brands"
version: "1.0.0"
slug: "staysharp_hassio_mariadb"
url: "https://github.com/UkDC/StaySharp-Hassio-MariaDB"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: services
boot: auto
ports:
  8000/tcp: 8000
webui: "http://[HOST]:[PORT:8000]"
host_network: false
options:
  db_host: "core-mariadb"
  db_port: 3306
  db_name: "homeassistant"
  db_user: "user"
  db_password: "password"
  create_superuser: false
  superuser_username: "admin"
  superuser_email: "admin@example.com"
  superuser_password: "adminpassword"
schema:
  db_host:
    type: str
    required: true
    default: "core-mariadb"
  db_port:
    type: int
    required: true
    default: 3306
  db_name:
    type: str
    required: true
    default: "homeassistant"
  db_user:
    type: str
    required: true
    default: "user"
  db_password:
    type: str
    required: true
    default: "password"
  create_superuser:
    type: bool
    required: true
    default: false
  superuser_username:
    type: str
    required: true
    default: "admin"
    selector:
      text:
        type: text
    advanced: true
  superuser_email:
    type: str
    required: true
    default: "admin@example.com"
    selector:
      text:
        type: text
    advanced: true
  superuser_password:
    type: str
    required: true
    default: "adminpassword"
    selector:
      password: {}
    advanced: true

full_access: false

documentation: "README.md"
icon: "icon.png"
logo: "logo.png"

